export const theme = {
  colors: {
    primary: '#6B9DFC',
    primaryDark: '#4A7FED',
    background: '#F5F7FA',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    onBackground: '#1A1A2E',
    onSurface: '#1A1A2E',
    onSurfaceLight: '#8E8E9A',
    border: '#E8ECF0',
    borderLight: '#F0F2F5',
    accent: '#FF8A65',
    success: '#4CAF50',
    warning: '#FFB74D',
    danger: '#EF5350',
    tabActive: '#6B9DFC',
    tabInactive: '#C4C4C4',
  },
  typography: {
    fontFamily: 'System',
    displayLarge: { fontSize: 34, fontWeight: '700' as const, letterSpacing: -1 },
    displayMedium: { fontSize: 28, fontWeight: '600' as const, letterSpacing: -0.5 },
    headlineLarge: { fontSize: 24, fontWeight: '700' as const, letterSpacing: -0.5 },
    headlineMedium: { fontSize: 20, fontWeight: '600' as const, letterSpacing: 0 },
    titleLarge: { fontSize: 18, fontWeight: '600' as const, letterSpacing: 0 },
    titleMedium: { fontSize: 16, fontWeight: '500' as const, letterSpacing: 0 },
    bodyLarge: { fontSize: 16, fontWeight: '400' as const, lineHeight: 26 },
    bodyMedium: { fontSize: 14, fontWeight: '400' as const, lineHeight: 22 },
    labelLarge: { fontSize: 14, fontWeight: '500' as const, letterSpacing: 0 },
    labelMedium: { fontSize: 12, fontWeight: '500' as const, letterSpacing: 0.5 },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  shadows: {
    soft: {
      shadowColor: '#1A1A2E',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    medium: {
      shadowColor: '#1A1A2E',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 5,
    },
  },
} as const;

export type Theme = typeof theme;